### ISSUE TITLE
It's the first time I've seen it and tried it, but there's a part I don't understand

### ISSUE THREAD

**Issue by MAKER-park** [jzkmath/Arduino-MIDI-Stepper-Motor-Instrument#1]
Hello! Thank you so much for giving us a good example. I'm trying to follow along.
Currently, the Arduino code uses a file called MIDI_Stepper_V1.ino. Yes, this is the arduino code you uploaded. I uploaded the code and checked the name of midi steeper using dfu mode.
By the way... from this point on, if you input a song using both loop midi and hairless MIDI, will the step motor move according to the song?

I don't understand the explanation of that part well. Any help or a video or reference that can be used would be appreciated!

**Comment by jzkmath** [comment]
Once you have programmed the device and it shows up in the device manager as the Stepper Synth, it is now seen as a MIDI device. The reason you do the DFU programmer process is so that your computer treats it like a MIDI device instead of a simple serial device. The process can also be used to make an Arduino look like other peripherals like a mouse or keyboard.
But back to your question, to understand how to use it you need to understand how to use a MIDI device and somewhat how it works. MIDI is simply a standard that electronic musical instruments use. It is actually a UART communication at 31250 baud. There are various pieces of software that can interface with MIDI, most of them being DAWs (Digital Audio Workstation) Some of these would include Ableton, FL Studio and Logic. 
The way I normally work with the stepper synth is by using two pieces of software: MuseScore and Notation Player 4. I use MuseScore to create and edit the MIDI files and then I use Player 4 to transmit the MIDI data to the machine.
MIDI has a series of ports and channels. Each MIDI port can have up to 16 channels, so in the case of the stepper synth it uses port 1 with channels 1 through 4, each channel corresponding to a motor. If you use MuseScore to edit the file, you can use the mixer to set the proper channel before exporting the MIDI file for use with Player 4. To get Player 4 set up, go to Setup -> MIDI Devices Quick Setup and make sure it is set to the stepper synth. After that it should work.

As for loop MIDI and hairless MIDI, those are meant to be an alternative for the DFU method. They allow you to send MIDI data through the COM port on the Arduino without the computer seeing it as a MIDI device. If you used the DFU method they are not needed.

All we are trying to do is send Note on and Note off commands to get it to play a song. If you are struggling with understanding this then a quick search on MIDI on YouTube will go a long way. 

Hope that is helpful!

**Comment by MAKER-park** [comment]
thanks to advice me...
so i one more wonder how to use it...
![image](https://user-images.githubusercontent.com/18068835/97424081-8b00d680-1953-11eb-94b0-335f28e87ec4.png)
is this..  midi steeper making device.. and test stepmotor done... but what is mean serial port...  is connection is midi stepper <-> midi program??? 

can you show example hairless midi setting...

**Comment by jzkmath** [comment]
Like I said before, MIDI is technically a type of Serial Connection. If you already made the Arduino into a MIDI device then you do not need Hairless MIDI.
If you didn't do the DFU programming, then you set the Serial port to be your Arduino and the MIDI ports is what you interface with your software like Player 4 or DAW.
I would seriously look up what Serial (or UART) is because I think you are getting confused as to what these are. 

To reiterate: An Arduino when plugged into a computer by default is seen as a Serial/UART device with a given COM Port. This is based on the older RS-232 standard used on older PCs for certain devices like printers. The port looked like this:
![image](https://user-images.githubusercontent.com/12432422/97461871-8b2db180-1914-11eb-9db1-63300118cdbd.png)
This was since replaced with USB (Universal SERIAL Bus). Programs that run MIDI are looking for a specific device and normally can't connect to a COM port, hence the use of Hairless MIDI. It makes the COM port look like a MIDI port.
We can simplify this by reprogramming the DFU using MucoLUFA which makes the Arduino turn into an actual MIDI device. 
A similar Arduino project is where you turn the arduino into a keyboard or mouse. When you plug a keyboard or mouse into your computer, it knows what it is and acts accordingly. The arduino is a Serial device but can be changed by reprogramming the 8u2 chip.

It makes a lot more sense if you understand what midi and serial is.

Again, if in the device manager the Arduino comes up as the Stepper Synth and not Arduino, then do not use Hairless MIDI. You don't need it. Its better for testing anyways!
