### ISSUE TITLE
Fourth motor

### ISSUE THREAD

**Issue by alana314** [jzkmath/Arduino-MIDI-Stepper-Motor-Instrument#2]
Hi,
Thanks for this! I'm having trouble getting my fourth motor firing, but the first three fire ok. Is there anything I need to do for the fourth motor? It's marked 'A' on the CNC shield, and it's pins 12/13?
I have a new version of the MIDI Sketch that accepts polyphonic input on one channel if you'd like me to submit a PR?
https://www.instagram.com/p/CP67SQZJ6rd/

**Comment by jzkmath** [comment]
The best way to figure out what the problem is would be to see if you can get the fourth motor turning with another sketch. All you would need to do is enable the drivers by pulling the enable pin low, then doing a simple "blink" code on the step pin. You might want to double check the step pin using a multimeter just to be sure.
I dont know too much about the mechanics of the pull request, but if there s a way to add it alongside the original code (like another folder for the polyphonic version) then go ahead.

**Comment by EpicLPer** [comment]
You have to jumper the bottom left contacts in pairs together on the CNC shield to get the 4th working, was wondering for hours too :)
![image](https://user-images.githubusercontent.com/8442196/121581756-85618800-ca2e-11eb-897e-664926bf95a1.jpg)

**Comment by alana314** [comment]
Thank you both!!
